// Example appliance payload for tests and API documentation
export default {
  companyName: 'ACME',
  companyContactName: 'John Doe',
  companyContactEmail: 'john@acme.com',
  companyAlternateEmail: 'alt@acme.com',
  companyPhone: '+447537328906',
  isUkBased: true,
  companyAddress: '123 Street',
  companyAddressLine1: '456 Factory Road',
  companyAddressLine2: 'Unit 7',
  companyAddressCity: 'Birmingham',
  companyAddressCounty: 'West Midlands',
  companyAddressPostcode: 'B1 2AB',
  modelName: 'Model X',
  modelNumber: 123,
  applianceType: 'heat',
  isVariant: false,
  existingAuthorisedAppliance: 'Old Model',
  nominalOutput: 10,
  //   multiFuelAppliance: false,
  allowedFuels: ['Wood Logs', 'Wood Pellets', 'Wood Chips', 'Other'],
  instructionManual: 'manual.pdf',
  instructionManualTitle: 'Manual X',
  instructionManualDate: '2026-02-03',
  instructionManualVersion: 'Version 1',
  instructionManualAdditionalInfo: 'Extra info',
  declaration: true,
  testReport: 'TR-001',
  technicalDrawings: 'drawing.pdf',
  ceMark: 'CE123',
  airControlModifications:
    'Must be fitted with the supplied secondary air control limiters'
}
