// Example appliance payload for tests and API documentation
export default {
  companyName: 'ACME',
  companyContactName: 'John Doe',
  companyContactEmail: 'john@acme.com',
  companyAlternateEmail: 'alt@acme.com',
  companyPhone: '+447537328906',
  isUkBased: true,
  companyAddress: '123 Street',
  companyAddressLine1: '456 Factory Road',
  companyAddressLine2: 'Unit 7',
  companyAddressCity: 'Birmingham',
  companyAddressCounty: 'West Midlands',
  companyAddressPostcode: 'B1 2AB',
  modelName: 'Model X',
  modelNumber: '123',
  applianceType: 'heat',
  isVariant: false,
  existingAuthorisedAppliance: 'Old Model',
  nominalOutput: 10,
  allowedFuels: ['Wood Logs', 'Wood Pellets', 'Wood Chips', 'Other'],
  instructionManualTitle: 'Manual X',
  instructionManualDate: '2026-02-03',
  instructionManualVersion: 'Version 1',
  instructionManualAdditionalInfo: 'Extra info',
  declaration: true,
  submittedBy: 'John Doe',
  submittedDate: '2026-02-02',
  publishedDate: '2026-02-11',
  technicalApproval: 'Certified',
  ratedOutput: 10,
  testedOutputRated: 10.5,
  testedOutputLow: 5.2,
  smokeEmissionOutputRated: 2.3,
  smokeEmissionOutputLow: 1.1,
  englandApproval: 'Certified',
  scotlandApproval: 'Certified',
  walesApproval: 'Certified',
  nIrelandApproval: 'Certified',
  walesApprovedBy: 'Wales Approver',
  nIrelandApprovedBy: 'NI Approver',
  scotlandApprovedBy: 'Scotland Approver',
  englandApprovedBy: 'England Approver',
  walesDateFirstAuthorised: '2026-02-04',
  nIrelandDateFirstAuthorised: '2026-02-05',
  scotlandDateFirstAuthorised: '2026-02-06',
  englandDateFirstAuthorised: '2026-02-07',
  applicationId: 'APP-EXAMPLE-001'
}
