// Example appliance payload for tests and API documentation
export default {
  companyName: 'ACME',
  companyContactName: 'John Doe',
  companyContactEmail: 'john@acme.com',
  companyAlternateEmail: 'alt@acme.com',
  companyPhone: '+447537328906',
  isUkBased: true,
  companyAddress: '123 Street',
  companyAddressLine1: '456 Factory Road',
  companyAddressLine2: 'Unit 7',
  companyAddressCity: 'Birmingham',
  companyAddressCounty: 'West Midlands',
  companyAddressPostcode: 'B1 2AB',
  modelName: 'Model X',
  modelNumber: 123,
  applianceType: 'heat',
  isVariant: false,
  existingAuthorisedAppliance: 'Old Model',
  nominalOutput: 10,
  multiFuelAppliance: false,
  allowedFuels: ['Wood Logs', 'Wood Pellets', 'Wood Chips', 'Other'],
  testReport: 'TR-001',
  technicalDrawings: 'drawing.pdf',
  ceMark: 'CE123',
  instructionManual: 'manual.pdf',
  instructionManualTitle: 'Manual X',
  instructionManualDate: '2026-02-03',
  instructionManualVersion: 'Version 1',
  instructionManualAdditionalInfo: 'Extra info',
  airControlModifications:
    'Must be fitted with the supplied secondary air control limiters',
  declaration: true,
  submittedBy: 'Alice',
  publishedDate: '2026-02-03',
  submittedDate: '2026-02-01',
  technicalApproval: 'Certified',
  walesApproval: 'Certified',
  nIrelandApproval: 'Certified',
  scotlandApproval: 'Certified',
  englandApproval: 'Certified',
  walesApprovedBy: 'Bob',
  nIrelandApprovedBy: 'Charlie',
  scotlandApprovedBy: 'Dave',
  englandApprovedBy: 'Eve',
  walesDateFirstAuthorised: '2026-02-03',
  nIrelandDateFirstAuthorised: '2026-02-03',
  scotlandDateFirstAuthorised: '2026-02-03',
  englandDateFirstAuthorised: '2026-02-03'
}
