// Example fuel payload for tests and API documentation
export default {
  companyName: 'FuelCo',
  isUkBased: true,
  companyAddress: {
    line1: '789 Industrial Estate',
    line2: 'Building C',
    city: 'Manchester',
    county: 'Greater Manchester',
    postcode: 'M1 3CD'
  },
  companyContact: {
    name: 'Fuel Person',
    email: 'fuel@co.com',
    alternativeEmail: 'alt@co.com',
    phone: '+44753732896'
  },
  responsibleName: 'Rep Name',
  responsibleEmailAddress: 'rep@co.com',
  customerComplaints: false,
  fuelBagging: 'Bagged',
  //   baggedAtSource: true,
  manufacturerOrReseller: 'Manufacturer',
  fuelDescription: 'Premium pellets',
  originalFuelManufacturer: 'Fuels LTD',
  originalFuelNameOrBrand: 'FireFuel',
  changedFromOriginalFuel: false,
  changesMade: 'The fuels was turned into love hearts',
  resellBrandName: 'PelletBrand',
  fuelWeight: 20,
  fuelComposition: 'Wood 100%',
  sulphurContent: 0.7,
  manufacturingProcess: 'Kiln-dried',
  qualityControlSystem: 'ISO certified',
  brandNames: 'PelletBrand',
  declaration: true,
  submittedBy: 'Fuel Person',
  submittedDate: '2026-02-02',
  publishedDate: '2026-02-11',
  technicalReview: {
    status: 'accepted'
  },
  englandApproval: 'Certified',
  scotlandApproval: 'Certified',
  walesApproval: 'Certified',
  nIrelandApproval: 'Certified',
  walesApprovedBy: 'Wales Approver',
  nIrelandApprovedBy: 'NI Approver',
  scotlandApprovedBy: 'Scotland Approver',
  englandApprovedBy: 'England Approver',
  walesDateFirstAuthorised: '2026-02-04',
  nIrelandDateFirstAuthorised: '2026-02-05',
  scotlandDateFirstAuthorised: '2026-02-06',
  englandDateFirstAuthorised: '2026-02-07',
  walesDateLastUpdated: '2026-02-12',
  nIrelandDateLastUpdated: '2026-02-13',
  scotlandDateLastUpdated: '2026-02-14',
  englandDateLastUpdated: '2026-02-15',
  legacyRecord: true
}
