// Example fuel payload for tests and API documentation
export default {
  companyName: 'FuelCo',
  isUkBased: true,
  companyAddress: 'Some address',
  companyAddressLine1: '789 Industrial Estate',
  companyAddressLine2: 'Building C',
  companyAddressCity: 'Manchester',
  companyAddressCounty: 'Greater Manchester',
  companyAddressPostcode: 'M1 3CD',
  companyContactName: 'Fuel Person',
  companyContactEmail: 'fuel@co.com',
  companyAlternateEmail: 'alt@co.com',
  companyPhone: '+447537328906',
  responsibleName: 'Rep Name',
  responsibleEmailAddress: 'rep@co.com',
  customerComplaints: false,
  fuelBagging: 'Bagged',
  //   baggedAtSource: true,
  manufacturerOrReseller: 'Manufacturer',
  fuelDescription: 'Premium pellets',
  originalFuelManufacturer: 'Fuels LTD',
  originalFuelNameOrBrand: 'FireFuel',
  changedFromOriginalFuel: false,
  changesMade: 'The fuels was turned into love hearts',
  resellBrandName: 'PelletBrand',
  fuelWeight: 20,
  fuelComposition: 'Wood 100%',
  sulphurContent: 0.7,
  manufacturingProcess: 'Kiln-dried',
  qualityControlSystem: 'ISO certified',
  brandNames: 'PelletBrand',
  declaration: true,
  letterFromManufacturer: 'Letter.pdf',
  testReports: 'TR-F-122',
  fuelAdditionalDocuments: 'Extra.pdf'
}
