# To set up Sonar cloud follow https://github.com/DEFRA/cdp-documentation/blob/main/howto/sonarcloud.md
# Update properties in this file as per the howto instructions
# Uncomment properties in this .github/workflows/check-pull-request.yml
# Uncomment properties in this .github/workflows/publish.yml
# Uncomment properties in this .github/workflows/publish-hotfix.yml

sonar.projectKey=DEFRA_aqie-dc-backend
sonar.organization=defra

sonar.links.homepage=https://github.com/DEFRA/aqie-dc-backend
sonar.links.ci=https://github.com/DEFRA/aqie-dc-backend/actions
sonar.links.scm=https://github.com/DEFRA/aqie-dc-backend
sonar.links.issue=https://github.com/DEFRA/aqie-dc-backend/issues

sonar.sources=src/
sonar.exclusions=src/**/*.test.js, src/sample-data/*.js, src/routes/example.js, src/routes/health.js, src/migrations/**/*.js, src/common/helpers/cdp-uploader.js, src/routes/admin-import.js, src/routes/upload-callback.js, src/example-find.js, src/index.js, src/common/helpers/cdp-uploader.js, src/common/helpers/entity-config.js, src/common/helpers/s3-download.js, src/plugins/*.js,src/sqs/client.js,src/sqs/mapper.js,src/sqs/repeater.js,src/plugins/sqs-consumer.js, src/sample-data/**/*.js, src/routes/applications/get-applications-with-summary.js, src/routes/applications/get-counts.js, src/routes/appliances/create-appliance.js, src/routes/fuels/create-fuel.js, src/routes/applications/create-application.js, src/routes/appliances/get-all-appliances.js, src/routes/applications/get-all-applications.js, src/controllers/applications-controller.js, src/routes/appliances/search-appliances.js, src/routes/applications/search-applications.js, src/routes/fuels/search-fuels.js, src/controllers/fuels-controller.js, src/routes/appliances/get-appliance-by-id.js, src/routes/applications/get-application-by-id.js, src/routes/fuels/get-fuel-by-id.js, src/controllers/appliances-controller.js
  
sonar.tests=src/
sonar.test.inclusions=src/**/*.test.js

sonar.javascript.lcov.reportPaths=./coverage/lcov.info
